from __future__ import annotations

import time
from typing import Any


def init_runtime_metrics(
    *,
    run_id: str | None,
    run_started_at: str | None,
    session_id: int,
    task_id: str,
    task_text: str,
    domain: str,
    learning_mode: str,
    architecture_mode: str,
    bootstrap: bool,
    mixed_errors: bool,
    required_skill_refs: set[str],
    require_skill_read: bool,
    lessons_loaded: int,
    prerun_v2_ids: list[str],
    benchmark_placebo: bool,
    transfer_retrieval_policy: str,
    transfer_retrieval_max_results: int,
    transfer_retrieval_score_weight: float,
    doc_mode: str,
    doc_retrieval: str,
    doc_budget_tokens: int,
    doc_retriever_model: str | None,
    executor_docs: bool,
    judge_docs: bool,
    judge_diagnostic: bool,
    contract_gap_retry: bool,
    contract_gap_retry_steps: int,
    contract_gap_deterministic_recipes: bool,
    verifier_stack_enabled: bool,
    low_confidence_threshold: float,
    clarify_on_low_confidence: bool,
    max_low_confidence_probes: int,
    verification_spec: dict[str, Any],
    verification_spec_errors: list[str],
    self_edit_mode_active: bool,
    self_edit_refs: set[str],
    watchdog_allow_posttask_in_safe_mode: bool,
    model_executor: str,
    critic_model_for_run: str,
    effective_judge_model: str,
    loop_watchdog_state_path: str,
    loop_watchdog_state: Any,
    loop_watchdog_safe_mode_active: bool,
    loop_watchdog_stop_flag: bool,
    escalation_state: dict[str, Any],
    auto_escalate_critic: bool,
    docs_bundle: Any,
    docs_selected_source_ids: list[str],
    docs_prompt_available: bool,
    docs_executor_block: str,
    docs_judge_block: str,
    docs_read_error_entries: list[dict[str, Any]],
    llm_backend: str,
    benchmark_deterministic: bool,
    benchmark_promoted_only: bool,
    runtime_candidate_policy: str,
    runtime_candidate_policy_effective: str,
    promoted_warmup_fallback: bool,
    legacy_lessons_enabled: bool,
    runtime_temperature: float | None,
    memory_v2_demo_mode: bool,
) -> dict[str, Any]:
    return {
        "run_id": str(run_id or ""),
        "run_started_at": str(run_started_at or ""),
        "run_ended_at": None,
        "run_status": "started",
        "run_error_summary": "",
        "session_id": session_id,
        "task_id": task_id,
        "task": task_text,
        "domain": domain,
        "learning_mode": learning_mode,
        "architecture_mode": architecture_mode,
        "bootstrap": bootstrap,
        "mixed_errors": mixed_errors,
        "steps": 0,
        "tool_actions": 0,
        "tool_errors": 0,
        "no_tool_call_steps": 0,
        "no_tool_call_steps_by_backend": {},
        "no_tool_recovery_prompts": 0,
        "no_tool_same_failure_streak": 0,
        "no_tool_same_failure_streak_max": 0,
        "no_tool_last_failure_signature": "",
        "sdk_no_tool_continuity_resets": 0,
        "sdk_no_tool_continuity_reset_steps": [],
        "sdk_reasoning_only_turns": 0,
        "sdk_reasoning_only_output_tokens": 0,
        "sdk_no_tool_retry_attempted": 0,
        "sdk_no_tool_retry_succeeded": 0,
        "sdk_no_tool_same_failure_streak": 0,
        "sdk_no_tool_same_failure_streak_max": 0,
        "tool_validation_errors": 0,
        "tool_validation_retry_attempts": 0,
        "tool_validation_retry_capped_events": 0,
        "error_count": 0,
        "skill_gate_blocks": 0,
        "skill_reads": 0,
        "required_skill_refs": sorted(required_skill_refs),
        "require_skill_read": require_skill_read,
        "lessons_loaded": lessons_loaded,
        "v2_lessons_loaded": len(prerun_v2_ids),
        "v2_prerun_lesson_ids": prerun_v2_ids,
        "v2_prerun_lesson_activations": len(prerun_v2_ids),
        "v2_prerun_placebo_applied": bool(benchmark_placebo and prerun_v2_ids),
        "lesson_activations": len(prerun_v2_ids),
        "v2_lesson_activations": len(prerun_v2_ids),
        "v2_lesson_activations_effective": 0 if benchmark_placebo else len(prerun_v2_ids),
        "v2_lesson_activations_placebo": len(prerun_v2_ids) if benchmark_placebo else 0,
        "v2_lesson_activations_by_step": {},
        "v2_lesson_activations_by_step_effective": {},
        "v2_lesson_activations_per_run": 0,
        "v2_lesson_activations_per_run_effective": 0,
        "v2_lesson_activation_rate": 0.0,
        "v2_lesson_activation_lane_counts": {},
        "v2_lesson_activation_lane_counts_effective": {},
        "v2_error_events": 0,
        "v2_retrieval_help_ratio": 0.0,
        "v2_retrieval_help_ratio_effective": 0.0,
        "v2_transfer_retrieval_enabled": transfer_retrieval_policy != "off",
        "v2_transfer_retrieval_policy": transfer_retrieval_policy,
        "v2_transfer_retrieval_max_results": transfer_retrieval_max_results,
        "v2_transfer_retrieval_score_weight": transfer_retrieval_score_weight,
        "doc_mode": doc_mode,
        "doc_retrieval_mode": doc_retrieval,
        "doc_budget_tokens": doc_budget_tokens,
        "doc_retriever_model": str(doc_retriever_model or "").strip() or None,
        "executor_docs": bool(executor_docs),
        "judge_docs": bool(judge_docs),
        "judge_diagnostic": bool(judge_diagnostic),
        "contract_gap_retry_enabled": bool(contract_gap_retry),
        "contract_gap_retry_steps_budget": int(contract_gap_retry_steps),
        "contract_gap_deterministic_recipes_enabled": bool(contract_gap_deterministic_recipes),
        "verifier_stack_enabled": bool(verifier_stack_enabled),
        "verifier_low_confidence_threshold": round(float(low_confidence_threshold), 3),
        "verifier_clarify_on_low_confidence": bool(clarify_on_low_confidence),
        "verifier_max_low_confidence_probes": int(max_low_confidence_probes),
        "verifier_spec_source": str(verification_spec.get("source", "")),
        "verifier_spec_source_path": str(verification_spec.get("source_path", "")),
        "verifier_spec_exact_output_lines": int(len(verification_spec.get("exact_output_lines", []) or [])),
        "verifier_spec_required_files": int(len(verification_spec.get("required_files", []) or [])),
        "verifier_spec_required_file_patterns": int(
            sum(
                len(row.get("patterns", []))
                for row in (verification_spec.get("required_file_content_patterns", []) or [])
                if isinstance(row, dict)
            )
        ),
        "verifier_spec_required_queries": int(len(verification_spec.get("required_queries", []) or [])),
        "verifier_confidence_base": None,
        "verifier_low_confidence_triggered": False,
        "verifier_probe_status": "not_run",
        "verifier_probe_results": [],
        "verifier_probe_failures": 0,
        "verifier_override_applied": False,
        "verifier_clarifying_question": "",
        "contract_gap_retry_attempts": 0,
        "contract_gap_retry_triggered": 0,
        "contract_gap_unresolved_count_prestop": 0,
        "contract_gap_unresolved_count_final": 0,
        "contract_gap_deterministic_hint_count": 0,
        "contract_retry_repair_observed": False,
        "contract_retry_repair_steps": [],
        "contract_validator_postretry_runs": 0,
        "contract_validator_postretry_last_status": "not_run",
        "contract_validator_postretry_last_trigger": "",
        "contract_closure_checks": 0,
        "contract_closure_check_failures": 0,
        "contract_closure_check_last_status": "not_run",
        "contract_closure_check_last_missing": [],
        "contract_validator_runs": 0,
        "contract_validator_last_status": "none",
        "contract_validator_query_ids": [],
        "docs_raw_count": len(docs_bundle.raw_docs),
        "docs_selected_chunks_count": len(docs_bundle.selected_chunks),
        "docs_selected_source_ids": docs_selected_source_ids,
        "docs_brief_chars": len(docs_bundle.brief),
        "docs_brief_strategy": docs_bundle.brief_strategy,
        "docs_distillation_used": docs_bundle.brief_strategy == "lossy_llm",
        "docs_prompt_available": docs_prompt_available,
        "docs_executor_prompt_chars": len(docs_executor_block),
        "docs_judge_prompt_chars": len(docs_judge_block),
        "docs_executor_prompt_injected": bool(docs_executor_block),
        "docs_judge_prompt_injected": bool(docs_judge_block),
        "docs_read_error_count": len(docs_read_error_entries),
        "docs_read_errors": docs_read_error_entries,
        "llm_backend": llm_backend,
        "benchmark_deterministic": bool(benchmark_deterministic),
        "benchmark_promoted_only": bool(benchmark_promoted_only),
        "benchmark_placebo": bool(benchmark_placebo),
        "runtime_candidate_policy": runtime_candidate_policy,
        "runtime_candidate_policy_effective": runtime_candidate_policy_effective,
        "runtime_promoted_warmup_fallback": bool(promoted_warmup_fallback),
        "legacy_lessons_enabled": bool(legacy_lessons_enabled),
        "runtime_temperature": runtime_temperature,
        "v2_transfer_lane_activations": 0,
        "v2_reflection_prompts": 0,
        "v2_reflection_reasons": [],
        "v2_structured_fallback_lessons": 0,
        "v2_schema_rejection_counts": {
            "missing_trigger_gap_signature": 0,
            "unbound_trigger_gap_signature": 0,
            "missing_action_template": 0,
            "invalid_action_template_placeholder": 0,
            "invalid_action_template_shape": 0,
            "invalid_action_template_tool": 0,
            "missing_expected_evidence": 0,
            "expected_evidence_unanchored": 0,
            "missing_structured_gap_fields": 0,
        },
        "v2_dependency_fallback_checks": 0,
        "v2_promoted": 0,
        "v2_suppressed": 0,
        "v2_fingerprint_recurrence_before": 0,
        "v2_fingerprint_recurrence_after": 0,
        "lessons_generated": 0,
        "v2_lessons_generated": 0,
        "posttask_patch_attempted": False,
        "self_edit_mode": bool(self_edit_mode_active),
        "self_edit_targets": sorted(self_edit_refs),
        "self_edit_forced_direct_mode": False,
        "self_edit_gate_events": 0,
        "posttask_skill_patching_skipped_by_mode": False,
        "posttask_skill_patching_skip_reason": None,
        "posttask_candidates_queued": 0,
        "posttask_patch_applied": 0,
        "posttask_rejection_counts": {
            "parse_fail": 0,
            "required_digest_mismatch": 0,
            "duplicate_jaccard": 0,
            "replace_miss": 0,
        },
        "auto_promotion_applied": 0,
        "auto_promotion_reason": None,
        "memory_v2_demo_mode": bool(memory_v2_demo_mode),
        "executor_model": model_executor,
        "critic_model": critic_model_for_run,
        "judge_model": effective_judge_model,
        "eval_score": 0.0,
        "eval_reasons": [],
        "eval_passed": False,
        "deterministic_probe_source": "none",
        "deterministic_probe_applicable": False,
        "deterministic_probe_passed": False,
        "deterministic_probe_score": 0.0,
        "deterministic_probe_reasons": [],
        "deterministic_probe_evidence": {},
        "verification_spec_source": str(verification_spec.get("source", "none")) if verification_spec is not None else "none",
        "verification_spec_errors": list(verification_spec_errors),
        "judge_score": None,
        "judge_passed": None,
        "judge_invoked": False,
        "judge_reasons": [],
        "judge_doc_grounding": [],
        "judge_critique": "",
        "judge_fail_probe_pass": False,
        "judge_pass_probe_fail": False,
        "critic_raw_lessons": [],
        "critic_filtered_lessons": [],
        "critic_rejected_lessons": [],
        "critic_generation_error": "",
        "critic_generation_parsed_items": 0,
        "critic_generation_raw_chars": 0,
        "v2_generation_error": "",
        "v2_generation_parsed_items": 0,
        "v2_generation_raw_chars": 0,
        "loop_watchdog_enabled": True,
        "loop_watchdog_state_path": str(loop_watchdog_state_path),
        "loop_watchdog_safe_mode_initial": bool(loop_watchdog_state.safe_mode_active),
        "loop_watchdog_safe_mode_active": bool(loop_watchdog_safe_mode_active),
        "loop_watchdog_safe_mode_triggered": False,
        "loop_watchdog_failure_signals": [],
        "loop_watchdog_disable_self_edit": False,
        "loop_watchdog_disable_posttask_patching": False,
        "loop_watchdog_disable_posttask_patching_effective": False,
        "watchdog_allow_posttask_in_safe_mode": bool(watchdog_allow_posttask_in_safe_mode),
        "loop_watchdog_stop_flag": bool(loop_watchdog_stop_flag),
        "loop_watchdog_repeated_hard_failure_signatures": 0,
        "loop_watchdog_contract_gap_unresolved_count": 0,
        "loop_watchdog_rejection_streak_initial": int(loop_watchdog_state.rejection_streak),
        "loop_watchdog_rejection_streak_final": int(loop_watchdog_state.rejection_streak),
        "loop_watchdog_safe_mode_failure_streak": int(loop_watchdog_state.safe_mode_failure_streak),
        "loop_watchdog_posttask_rejection_total": 0,
        "loop_watchdog_state_persisted": False,
        "critic_no_updates_streak": int(escalation_state.get("critic_no_updates_streak", 0)),
        "low_score_streak": int(escalation_state.get("low_score_streak", 0)),
        "escalation_state": {
            "tier": escalation_state.get("tier"),
            "override_runs_remaining": escalation_state.get("override_runs_remaining"),
            "last_trigger": escalation_state.get("last_trigger"),
            "auto_escalate_critic": auto_escalate_critic,
        },
        "usage": [],
        "time_start": time.time(),
    }

