from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable

from tracks.cli_sqlite.agent_runtime_eval_phase import run_eval_and_judge_phase
from tracks.cli_sqlite.agent_runtime_posttask_phase import run_posttask_phase
from tracks.cli_sqlite.agent_runtime_verifier_watchdog import run_verifier_and_watchdog_phase


@dataclass(frozen=True)
class PostExecutionPhaseOutcome:
    events: list[dict[str, Any]]
    eval_result: Any
    probe_result: Any
    final_unresolved_gaps: list[dict[str, Any]]
    judge_input_bundle: dict[str, Any] | None
    judge_payload_bundle: dict[str, Any] | None
    repeated_error_signatures: list[str]
    loop_watchdog_decision: Any
    loop_watchdog_safe_mode_active: bool
    loop_watchdog_failure_signals: list[str]
    loop_watchdog_stop_flag: bool
    effective_self_edit_mode_active: bool
    watchdog_disable_posttask_effective: bool
    critic_no_updates: bool
    v2_candidate_lessons: list[dict[str, Any]]
    promoted_lesson_ids: list[str]
    suppressed_lesson_ids: list[str]


def run_post_execution_phases(
    *,
    # Eval + judge inputs
    adapter: Any,
    has_contract: bool,
    contract_gap_retry: bool,
    contract_gap_retries_used: int,
    paths: Any,
    workspace: Any,
    task_id: str,
    task_text: str,
    domain: str,
    llm_backend: str,
    judge_diagnostic: bool,
    effective_judge_model: str,
    runtime_temperature: float | None,
    verification_spec: dict[str, Any],
    verification_spec_errors: list[Any],
    client: Any,
    docs_judge_block: str,
    metrics: dict[str, Any],
    tasks_root: Any,
    canonicalize_hotfix_transfer_eval_events_fn: Callable[..., Any],
    read_events_fn: Callable[..., Any],
    evaluate_cli_session_fn: Callable[..., Any],
    verification_spec_for_probe_fn: Callable[..., Any],
    run_deterministic_probes_fn: Callable[..., Any],
    unresolved_contract_gaps_fn: Callable[..., Any],
    llm_judge_fn: Callable[..., Any],
    clone_json_fn: Callable[..., Any],
    deterministic_probe_result_cls: Any,
    # Watchdog inputs
    verifier_stack_enabled: bool,
    low_confidence_threshold: float,
    clarify_on_low_confidence: bool,
    max_low_confidence_probes: int,
    run_error_events: list[Any],
    loop_watchdog_state: Any,
    loop_watchdog_state_path: Any,
    posttask_learn: bool,
    self_edit_mode_active: bool,
    watchdog_allow_posttask_in_safe_mode: bool,
    run_id: str | None,
    session_id: int,
    learning_mode: str,
    sessions_root: Any,
    on_lifecycle_event: Callable[[str, dict[str, Any]], None] | None,
    clamp_fn: Callable[..., Any],
    dedupe_nonempty_text_rows_fn: Callable[..., Any],
    collect_event_text_blobs_fn: Callable[..., Any],
    run_required_files_probe_fn: Callable[..., Any],
    normalize_required_file_content_patterns_fn: Callable[..., Any],
    run_required_file_content_patterns_probe_fn: Callable[..., Any],
    normalize_required_queries_fn: Callable[..., Any],
    resolve_verification_db_path_fn: Callable[..., Any],
    run_required_query_probe_fn: Callable[..., Any],
    run_sqlite_gap_query_probe_fn: Callable[..., Any],
    build_low_confidence_clarifying_question_fn: Callable[..., Any],
    write_event_fn: Callable[..., Any],
    evaluate_watchdog_policy_fn: Callable[..., Any],
    loop_watchdog_snapshot_cls: Any,
    append_self_edit_gate_event_fn: Callable[..., Any],
    # Posttask inputs
    architecture_mode: str,
    memory_v2_demo_mode: bool,
    skill_manifest_entries: list[Any],
    routed_entries: list[Any],
    self_edit_manifest_entries: list[Any],
    read_skill_refs: set[str],
    final_unresolved_gaps_for_adaptive: list[dict[str, Any]] | None,
    repeated_error_signatures_seed: list[str],
    structured_lessons_required: bool,
    contract_gap_deterministic_recipes: bool,
    opaque_tools: bool,
    benchmark_placebo: bool,
    lesson_activation_records: list[dict[str, Any]],
    contradiction_loser_counts: dict[str, int],
    model_executor: str,
    critic_model_for_run: str,
    posttask_mode: str,
    track_root: Any,
    skills_root: Any,
    manifest_path: Any,
    queue_path: Any,
    promoted_path: Any,
    lessons_path: Any,
    lessons_v2_path: Any,
    promotion_min_runs: int,
    promotion_min_delta: float,
    promotion_max_regressions: int,
    max_steps: int,
    doc_mode: str,
    docs_bundle: Any,
    knowledge_provider: Any,
    deps: dict[str, Any],
) -> PostExecutionPhaseOutcome:
    eval_outcome = run_eval_and_judge_phase(
        adapter=adapter,
        has_contract=has_contract,
        contract_gap_retry=bool(contract_gap_retry),
        contract_gap_retries_used=contract_gap_retries_used,
        paths=paths,
        workspace=workspace,
        task_id=task_id,
        task_text=task_text,
        domain=domain,
        llm_backend=llm_backend,
        judge_diagnostic=bool(judge_diagnostic),
        effective_judge_model=effective_judge_model,
        runtime_temperature=runtime_temperature,
        verification_spec=verification_spec,
        verification_spec_errors=verification_spec_errors,
        client=client,
        docs_judge_block=docs_judge_block,
        metrics=metrics,
        tasks_root=tasks_root,
        canonicalize_hotfix_transfer_eval_events_fn=canonicalize_hotfix_transfer_eval_events_fn,
        read_events_fn=read_events_fn,
        evaluate_cli_session_fn=evaluate_cli_session_fn,
        verification_spec_for_probe_fn=verification_spec_for_probe_fn,
        run_deterministic_probes_fn=run_deterministic_probes_fn,
        unresolved_contract_gaps_fn=unresolved_contract_gaps_fn,
        llm_judge_fn=llm_judge_fn,
        clone_json_fn=clone_json_fn,
        deterministic_probe_result_cls=deterministic_probe_result_cls,
    )
    events = eval_outcome.events
    eval_result = eval_outcome.eval_result
    probe_result = eval_outcome.probe_result
    final_unresolved_gaps = eval_outcome.final_unresolved_gaps
    judge_input_bundle = eval_outcome.judge_input_bundle
    judge_payload_bundle = eval_outcome.judge_payload_bundle

    verifier_watchdog_outcome = run_verifier_and_watchdog_phase(
        has_contract=has_contract,
        verifier_stack_enabled=bool(verifier_stack_enabled),
        low_confidence_threshold=float(low_confidence_threshold),
        clarify_on_low_confidence=bool(clarify_on_low_confidence),
        max_low_confidence_probes=int(max_low_confidence_probes),
        task_id=task_id,
        domain=domain,
        workspace=workspace,
        verification_spec=verification_spec,
        events=events,
        eval_result=eval_result,
        probe_result=probe_result,
        final_unresolved_gaps=final_unresolved_gaps,
        run_error_events=run_error_events,
        loop_watchdog_state=loop_watchdog_state,
        loop_watchdog_state_path=loop_watchdog_state_path,
        posttask_learn=bool(posttask_learn),
        self_edit_mode_active=bool(self_edit_mode_active),
        watchdog_allow_posttask_in_safe_mode=bool(watchdog_allow_posttask_in_safe_mode),
        run_id=run_id,
        session_id=session_id,
        learning_mode=learning_mode,
        sessions_root=sessions_root,
        metrics=metrics,
        paths=paths,
        on_lifecycle_event=on_lifecycle_event,
        clamp_fn=clamp_fn,
        dedupe_nonempty_text_rows_fn=dedupe_nonempty_text_rows_fn,
        collect_event_text_blobs_fn=collect_event_text_blobs_fn,
        run_required_files_probe_fn=run_required_files_probe_fn,
        normalize_required_file_content_patterns_fn=normalize_required_file_content_patterns_fn,
        run_required_file_content_patterns_probe_fn=run_required_file_content_patterns_probe_fn,
        normalize_required_queries_fn=normalize_required_queries_fn,
        resolve_verification_db_path_fn=resolve_verification_db_path_fn,
        run_required_query_probe_fn=run_required_query_probe_fn,
        run_sqlite_gap_query_probe_fn=run_sqlite_gap_query_probe_fn,
        build_low_confidence_clarifying_question_fn=build_low_confidence_clarifying_question_fn,
        write_event_fn=write_event_fn,
        evaluate_watchdog_policy_fn=evaluate_watchdog_policy_fn,
        loop_watchdog_snapshot_cls=loop_watchdog_snapshot_cls,
        append_self_edit_gate_event_fn=append_self_edit_gate_event_fn,
    )
    repeated_error_signatures = list(verifier_watchdog_outcome.repeated_error_signatures)
    loop_watchdog_decision = verifier_watchdog_outcome.loop_watchdog_decision
    loop_watchdog_safe_mode_active = verifier_watchdog_outcome.loop_watchdog_safe_mode_active
    loop_watchdog_failure_signals = verifier_watchdog_outcome.loop_watchdog_failure_signals
    loop_watchdog_stop_flag = verifier_watchdog_outcome.loop_watchdog_stop_flag
    effective_self_edit_mode_active = verifier_watchdog_outcome.effective_self_edit_mode_active
    watchdog_disable_posttask_effective = verifier_watchdog_outcome.watchdog_disable_posttask_effective

    posttask_outcome = run_posttask_phase(
        posttask_learn=bool(posttask_learn),
        client=client,
        architecture_mode=architecture_mode,
        memory_v2_demo_mode=bool(memory_v2_demo_mode),
        skill_manifest_entries=skill_manifest_entries,
        loop_watchdog_decision=loop_watchdog_decision,
        watchdog_disable_posttask_effective=bool(watchdog_disable_posttask_effective),
        metrics=metrics,
        events=events,
        routed_entries=routed_entries,
        self_edit_manifest_entries=self_edit_manifest_entries,
        effective_self_edit_mode_active=bool(effective_self_edit_mode_active),
        task_text=task_text,
        eval_result=eval_result,
        session_id=session_id,
        task_id=task_id,
        domain=domain,
        read_skill_refs=read_skill_refs,
        learning_mode=learning_mode,
        runtime_temperature=runtime_temperature,
        final_unresolved_gaps=final_unresolved_gaps_for_adaptive or final_unresolved_gaps,
        run_error_events=run_error_events,
        repeated_error_signatures=repeated_error_signatures_seed or repeated_error_signatures,
        structured_lessons_required=bool(structured_lessons_required),
        contract_gap_deterministic_recipes=bool(contract_gap_deterministic_recipes),
        adapter=adapter,
        opaque_tools=bool(opaque_tools),
        benchmark_placebo=bool(benchmark_placebo),
        lesson_activation_records=lesson_activation_records,
        contradiction_loser_counts=contradiction_loser_counts,
        model_executor=model_executor,
        critic_model_for_run=critic_model_for_run,
        posttask_mode=posttask_mode,
        run_id=run_id,
        paths=paths,
        self_edit_mode_active=bool(self_edit_mode_active),
        promotion_min_runs=promotion_min_runs,
        promotion_min_delta=promotion_min_delta,
        promotion_max_regressions=promotion_max_regressions,
        max_steps=max_steps,
        sessions_root=sessions_root,
        track_root=track_root,
        skills_root=skills_root,
        manifest_path=manifest_path,
        queue_path=queue_path,
        promoted_path=promoted_path,
        lessons_path=lessons_path,
        lessons_v2_path=lessons_v2_path,
        deps={
            "docs_bundle": docs_bundle,
            "doc_mode": doc_mode,
            "knowledge_provider": knowledge_provider,
            "_load_skill_snapshots": deps["_load_skill_snapshots"],
            "_build_critic_context_query": deps["_build_critic_context_query"],
            "_format_critic_context": deps["_format_critic_context"],
            "_serialize_lesson": deps["_serialize_lesson"],
            "generate_lessons": deps["generate_lessons"],
            "store_lessons": deps["store_lessons"],
            "prune_lessons": deps["prune_lessons"],
            "_allowed_action_tools_for_adapter": deps["_allowed_action_tools_for_adapter"],
            "_deterministic_gap_fix_recipes": deps["_deterministic_gap_fix_recipes"],
            "_validate_structured_model_lesson": deps["_validate_structured_model_lesson"],
            "_extract_action_template_from_legacy_lesson": deps["_extract_action_template_from_legacy_lesson"],
            "extract_tags": deps["extract_tags"],
            "lesson_record_cls": deps["LessonRecord"],
            "upsert_lesson_records": deps["upsert_lesson_records"],
            "_load_recent_eval_scores": deps["_load_recent_eval_scores"],
            "_clamp": deps["_clamp"],
            "load_lesson_records": deps["load_lesson_records"],
            "lesson_outcome_cls": deps["LessonOutcome"],
            "apply_outcomes": deps["apply_outcomes"],
            "propose_skill_updates": deps["propose_skill_updates"],
            "parse_reflection_response": deps["parse_reflection_response"],
            "self_edit_allowed_refs": deps["self_edit_allowed_refs"],
            "append_self_edit_gate_event": deps["append_self_edit_gate_event"],
            "apply_guarded_self_edit_updates": deps["apply_guarded_self_edit_updates"],
            "apply_skill_updates": deps["apply_skill_updates"],
            "queue_skill_update_candidates": deps["queue_skill_update_candidates"],
            "auto_promote_queued_candidates": deps["auto_promote_queued_candidates"],
            "write_event": deps["write_event"],
        },
    )

    return PostExecutionPhaseOutcome(
        events=events,
        eval_result=eval_result,
        probe_result=probe_result,
        final_unresolved_gaps=final_unresolved_gaps,
        judge_input_bundle=judge_input_bundle,
        judge_payload_bundle=judge_payload_bundle,
        repeated_error_signatures=list(posttask_outcome.repeated_error_signatures),
        loop_watchdog_decision=loop_watchdog_decision,
        loop_watchdog_safe_mode_active=bool(loop_watchdog_safe_mode_active),
        loop_watchdog_failure_signals=list(loop_watchdog_failure_signals),
        loop_watchdog_stop_flag=bool(loop_watchdog_stop_flag),
        effective_self_edit_mode_active=bool(effective_self_edit_mode_active),
        watchdog_disable_posttask_effective=bool(watchdog_disable_posttask_effective),
        critic_no_updates=bool(posttask_outcome.critic_no_updates),
        v2_candidate_lessons=list(posttask_outcome.v2_candidate_lessons),
        promoted_lesson_ids=list(posttask_outcome.promoted_lesson_ids),
        suppressed_lesson_ids=list(posttask_outcome.suppressed_lesson_ids),
    )
